name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: ${{ secrets.FOO }}
      - uses: ./action-b
        with:
          FOO: "Mavi"
      - name: "ktlint"
        uses: "vroy/gha-kotlin-linter@v1"